name: Auto message Issues
on: issues
jobs:
  greeting:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Hello @${{ github.actor }} , thank you for submitting an issue! 👍 We highly appreciate if you work on it as well.'
